#!/bin/sh
# Attach to existing tmux session or run $PROGRAM inside newly spawned one
# USAGE:	$ ln -s _tmuxify mutt && ./mutt

# The program's basename
name=${0##*/}
# Remove trailing underscore if present
name=${name#_}

tmux has -t "${name}" \
	&& tmux attach -t "${name}" \
	|| tmux new -n "${name}" -s "${name}" \
		# Run the actual program from $PATH ignoring the wrapper
		$(which --skip-tilde "${name}") ${@}
