#!/bin/sh
# Attach to existing tmux session or run $prog inside newly spawned one
# USAGE:	$ ln -s _tmuxify mutt && ./mutt

# The symlink's name specifies the program to run
prog=$(basename "${0}" | tail -c+2)

tmux has -t "${prog}" \
	&& tmux attach -t "${prog}" \
	|| tmux new -n "${prog}" -s "${prog}" \
		$(which --skip-tilde "${prog}") ${@}
