#!/bin/sh
# Build OpenBSD from source according to release(8)

set -eu

[ $(id -u) -ne 0 ] &&
	printf '%s: you must be root\n' "${0##*/}" 2>&1 &&
	exit 1

ask() {
	printf '%s? [yN]: ' "${1}" 1>&2
	read REPLY
	[ "${REPLY}" = y ]
}

_build() {
	exec 1>/dev/null
	set -x
	mount -s /usr/${X:-}obj
	time make -C"${DIR}" -s ${@}
}

build_base() {
	local DIR
	DIR=/usr/src
	_build obj
	mount -wu /usr
	_build build
	if ask 'run sysmerge'; then
		if ask '  diff mode'; then
			sysmerge -d
		else
			sysmerge
		fi
	fi
	if ask 'create device nodes'; then
		cd /dev && ./MAKEDEV all
	fi
	mount -ru /usr
}

build_kernel() {
	local DIR
	DIR=/sys/arch/"$(machine)"/compile/GENERIC.MP
	_build obj
	_build config
	_build
	if ask 'install kernel'; then
		_build install
	fi
}

build_xenocara() {
	DIR=/usr/xenocara
	X=x
	mount -wu /usr/X11R6
	_build bootstrap
	_build obj
	_build build
	mount -ru /usr/X11R6
}

for p in kernel base xenocara; do
	ask "build ${p}" && eval build_${p}
done

return 0
