#!/bin/sh
# Build OpenBSD from source according to release(8)

set -eu

[ $(id -u) -eq 0 ]

ask() {
	printf '%s? [yN]: ' "${1}"
	read REPLY
	[ "${REPLY}" = y ] || return 1
	return 0
}

build_base() {
	DIR=/usr/src
	(
	    set -x
	    mount -s /usr/obj
	    make -C"${DIR}" obj
	    make -C"${DIR}" build
	) 1>/dev/null
	if ask 'run sysmerge'; then
		ask '  diff mode' && sysmerge -d || sysmerge
	fi
}

build_kernel() {
	DIR=/sys/arch/$(machine)/compile/GENERIC.MP
	(
	    set -x
	    mount -s /usr/obj
	    make -C"${DIR}" obj
	    make -C"${DIR}" config
	    make -C"${DIR}"
	) 1>/dev/null
	ask 'install kernel' && make -C"${DIR}" install
}

ask 'build kernel' && build_kernel
ask 'build base' && build_base

return 0
