#!/bin/sh
# Check whether VPN connection is really active

abort() {
	printf '%s\n' "${1}" 1>&2
	exit 1
}

[ $(ls /run/openvpn*.pid 2> /dev/null | wc -w) -eq 0 ] && abort "OpenVPN not running"
[ -z "$(ip tuntap show)" ] && abort "tunnel device missing"

curl -4 https://ifcfg.me/all
printf '\n'
curl -6 https://ifcfg.me/all

