#!/bin/sh
# This script gets called through `status_display_program' in cmus(1)
# $CMUS_STATUS_FILE is declared in ~/.profile

# Keys:	status file url artist album discnumber tracknumber title date
while [ ${#} -ge 2 ]; do
	eval ${1}='${2}'
	shift 2
done

printf '%s\n%s - %s\n' "${status}" "${title}" "${artist}" \
	> "${CMUS_STATUS_FILE}"
