#!/bin/sh
# filter all URIs, show them in dmenu and copy selection to clipboard
# (mainly used by st's externalpipe patch)

tr --squeeze-repeats ' ,;<>\()"│' '\n' \
	| grep --text --ignore-case --extended-regexp \
		'(git|https?|s?ftp|rsync|ssh)://' \
	| sort --ignore-case --unique \
	| dmenu -f -i -l 10 \
	| tr --delete '\n' \
	| xsel --input
