#!/bin/sh
# get CPU fan speed in RPM

# platforn specific
sed -n '2s/speed:\t\t//p' /proc/acpi/ibm/fan

# alternatives
#grep speed: /proc/acpi/ibm/fan | cut -f3
#cut -f3 /proc/acpi/ibm/fan | sed -n 2p
