#!/bin/sh
# get local IP addresses otherwise 'down'

opt=-o
dev=

if [ ${#} -eq 1 ]; then
	[ ${1} = '-4' ] || [ ${1} = '-6' ] \
		&& opt="${opt} ${1}" \
		|| dev="dev ${1}"
elif [ ${#} -eq 2 ]; then
	opt="${opt} ${1}"
	dev="dev ${2}"
elif [ ${#} -ge 3 ]; then
	printf 'Usage: getip [-4|-6] [interface_name]\n'
	exit 1
fi

ip=$(ip ${opt} address show ${dev} primary up \
	| awk '{ print $4 }' \
	| cut -d/ -f1
)

printf '%s\n' "${ip:-down}"
