#!/bin/sh
# get title and artist from cmus if playing otherwise 'paused'

query=$(cmus-remote -Q \
		2>/dev/null \
		| head -n8
)

# quit if cmus is not running
[ -z "${query}" ] && exit 1

# get title and artist
IFS=$(printf '\v') read -r status title artist << _EOF_
$(printf '%s' "${query}" \
	| sed -n 's/^\(status\|tag \(title\|artist\)\) //p' \
	| tr '\n' '\v'
)
_EOF_

[ "${status}" = playing ] \
	&& echo "${title} - ${artist}" \
	|| echo paused
