#!/bin/sh
# get ALSA master volume in percentage
# (assumes that left and right channel are equal)

amixer get Master \
      | tail --lines=1 \
      | awk '{ print $5 }' \
      | tr --delete '[%]'
