#!/bin/sh
# Download music from libreboot's free music repository

[ ${#} -ne 1 ] && echo 'USAGE:\tlbmdl <destination>' 1>&2 && exit 1

remote=rsync://rsync.libreboot.org/music

printf '%s currently contains %sG of data.\n\n' \
	"${remote}" \
	"$(rsync -r "${remote}" \
		| awk '{ gsub(/,/,"",$2); s += $2 } END \
			{ print (s / 1073741824) }' \
	)"

# Mirror changes from remote repository to local destination folder
#	- Newer files won't be updated
#	- Files will never be deleted
rsync -r -u -l -H -m -I -h -P --exclude=index.php \
	"${remote}" \
	"${1}"
