#!/bin/sh
# Download Linux manual pages from manpages.debian.org and cache them
# under $LMANPATH, same usage as man(1).

die() {
	printf '%s: %s\n' "${0##*/}" "${2}" 1>&2
	exit ${1}
}

usage() {
	MANPATH= man -h man | sed -e '/^-*$/d' 1>&2
	exit ${1}
}

MKDIR() {
	[ -d "${1}" ] || mkdir -p "${1}" || exit ${?}
}

curlopts='--connect-timeout 3 -fs'

cache() {
	MKDIR "${2%/*}"
	# fetch new/update cached manual page
	curl ${curlopts} --compressed -Rz"${2}" -o"${2}" "${1}"
}

geturl() {
	curl ${curlopts} -LI "${1}" | sed -n s,^Location:\ ,,p |
		tr -d \\r | grep -Fv https://dyn.
}

# overwrite man(1) search path
export MANPATH="${LMANPATH:-${HOME}/.lman}"

# offline lookup, save error message
exec 3>&1
err=$(man "${@}" 2>&1 1>&3)
ret=${?}
exec 3>&-

# quit if some page was read
[ ${ret} -ne 5 ] && exit ${ret}

MKDIR "${MANPATH}"

# parse arguments for required API bits (name, section)
args=$(getopt acfhklwC:M:m:S:s: "${@}") || usage 5
set -- ${args}

while [ ${#} -ne 0 ]; do
	case "${1}" in
	-[acfhklw])
		shift;;
	-[Ss])
		eval ${1#-}arg=.${2};
		shift 2;;
	-[CMm])
		printf "'-%s %s' option ignored\n" ${1} "${2}" 1>&2
		shift 2;;
	--)
		shift
		break;;
	esac
done
[ -z "${@}" ] && usage 5


# API parameters
host=https://manpages.debian.org
suite=/unstable
## foo
name=/"${*}"
section=${sarg}${Sarg}
fmt=.gz
scheme="${host}${suite}${pkg}${name}${section}${lang}${fmt}"


## https://.../foo.1.en.gz
url=$(geturl "${scheme}")
[ -z "${url}" ] && die 1 "'${name#/}${section}' could not be found."

## foo.1
man=${url##*/} man=${man%.*} man=${man%.*}

## .../man1/foo.1
file="${MANPATH}"/man${man#*.}/${man}

## fetch missing page
cache "${url}" "${file}" || die 1 "Could not fetch ${file}."

exec man ${args}
