#!/bin/sh -euC
# Download Linux manual pages from manpages.debian.org and cache them
# under $LMANPATH, same usage as man(1).

die() {
	printf '%s: %s\n' "${0##*/}" "$*" 1>&2
	exit 1
}

usage() {
	MANPATH= man -h man | sed -e '/^-*$/d' 1>&2
	exit 5
}

curlopts='--connect-timeout 3 -fs'

cache() {
	mkdir -p "${2%/*}"
	curl ${curlopts} --compressed -Rz"$2" -o"$2" "$1"
	makewhatis
}

geturl() {
	curl ${curlopts} -LI "$1" | sed -n s,^Location:\ ,,p |
		tr -d \\r | grep -Fv https://dyn.
}

# overwrite man(1) search path
export MANPATH="${LMANPATH:-${HOME}/.lman}"

# offline lookup, save error message
exec 3>&1
ret=0
err=$(man "$@" 2>&1 1>&3) || ret=$?
exec 3>&-

# quit if some page was read
[ $ret -eq 5 ] || exit $ret

mkdir -p "${MANPATH}"

# parse arguments for required API bits (name, section)
while getopts acfhklwC:M:m:S:s: OPT; do
	case ${OPT} in
	[acfhklwCMm])	;;
	[Ss])		eval ${OPT}arg=.${OPTARG};;
	*)		usage;;
	esac
done
args="$@"
shift $((OPTIND - 1))

# turn `... 1 foo' into `... -s 1 foo'
case "$1" in
[1-9nl]|3am|3posix|3perl)	[ -n "${sarg:-}" ] && usage
				sarg=.${1}
				shift;;
esac
[ $# -eq 1 ] || usage

# API parameters
host=https://manpages.debian.org
suite=/unstable
# unused
pkg=
## foo
name=/"${1}"
section=${sarg:-}${Sarg:-}
lang=.en
fmt=.gz
scheme="${host}${suite}${pkg}${name}${section}${lang}${fmt}"


## https://.../foo.1.en.gz
url=$(geturl "$scheme")
[ -z "$url" ] && die "'${name#/}${section}' could not be found."

## foo.1
man=${url##*/} man=${man%.*} man=${man%.*}

## .../man1/foo.1
file="${MANPATH}"/man${man##*.}/${man}

## fetch missing page
cache "$url" "$file" || die "Could not fetch ${file}."

exec man $args
