#!/bin/sh
# Download Linux manual pages from manpages.debian.org and cache them
# for transparent offline usage.
# LMANPATH can be appended to MANPATH to provide "native" fallback.
# See man(1) and mandoc(1) for options

die() {
	printf '%s: %s\n' "${0##*/}" "${2}" 1>&2
	exit ${1}
}

usage() {
	cat << EOF 1>&2
usage: ${0##*/} [-c] [-O options] [-T output] [-r release] [-p package]
            [-s section] [-l language] name
EOF
	exit ${1}
}


cache() {
	# fetch new/update cached new manual page
	curl --connect-timeout 3 -fsRz"${1}" -o"${1}" "${2}"
}

geturl() {
	curl -fsLI "${1}" | grep ^Location | grep -Fv dyn.manpages |
		cut -d' ' -f2 | tr -d \\r
}


MKDIR() {
	[ -d "${1}" ] || mkdir -p "${1}" ||
		die 1 "${1} cannot be created."
}


args=$(getopt cl::s::O::T:: "${@}") || usage 2
set -- ${args}

host=https://manpages.debian.org
suite=/unstable
fmt=.gz
[ -t 0 ] && cflag=-a || cflag=-c

while [ ${#} -ne 0 ]; do
	case "${1}" in
	-c)	cflag=-c;	shift;;
	-O)	Oflag=-O"${2}";	shift 2;;
	-T)	Tflag=-T"${2}";	shift 2;;
	-r)	suite=/"${2}";	shift 2;;
	-p)	pkg=/"${2}";	shift 2;;
	-s)	section=."${2}";shift 2;;
	-l)	lang=."${2}";	shift 2;;
	--)			shift;	break;;
	esac
done

[ -z "${@}" ] && usage 5
MANDOC="mandoc ${cflag} ${Oflag} ${Tflag}"


lmanpath="${LMANPATH:-${HOME}/.lman}"
MKDIR "${lmanpath}"

# foo
name=/"${@}"
scheme="${host}${suite}${pkg}${name}${section}${lang}${fmt}"


# cache lookup
file=$(find "${lmanpath}" -type f -name "${name#/}${section:-.*}" |
	grep -E "${name#/}\.[1-9]p?m?$" | head -n1)

# cache hit
[ -n "${file}" ] && {
	# update
	url=$(geturl "${scheme%/*}/${file##*/}${lang}${fmt}")
	[ -n "${url}" ] && cache "${file}" "${url}"
	exec ${MANDOC} "${file}"
}


# cache miss
# https://.../foo.1.en.gz
url=$(geturl "${scheme}")
[ -z "${url}" ] && die 1 "No entry for ${name#/} in the manual."

# foo.1
man=${url##*/} man=${man%.*} man=${man%.*}

lmanpath="${lmanpath}"/man${man##*.}
MKDIR "${lmanpath}"

# ~/.lman/man1/foo.1
file="${lmanpath}"/${man}

# fetch
cache "${file}" "${url}" || die 1 "Could not fetch ${file}."
exec ${MANDOC} "${file}"
