#!/bin/sh
# lock the session

xset dpms force off
pkill -SIGKILL xbattmon
pkill -SIGKILL setdwmstat

slock ${@}

xbattmon &
setdwmstat &

[ -f ~/slock.jpg ] \
	&& sxiv -f -q ~/slock.jpg && mv -f ~/slock.jpg ~/slock-last.jpg
