#!/bin/sh
# lock screen and take care of related things

# turn off display and battery status
xset dpms force off && pkill -SIGKILL xbattmon

# lock screen
slock

# show battery status again
xbattmon &

# Show mugshot and save it if present
[ -f ~/slock.jpg ] && meh ~/slock.jpg && mv ~/slock.jpg ~/slock-last.jpg
