#!/bin/sh
# lock the session and save slock's mugshots

xset dpms force off

pkill -SIGSTOP xbattmon\|setdwmstat
slock ${@}
pkill -SIGCONT xbattmon\|setdwmstat

if [ -f /tmp/slock.jpg ]; then
	filepath=~/slock-pictures/slock-$(date +%F-%T).jpg
	mv -f /tmp/slock.jpg ${filepath} && sxiv -f -q ${filepath}
fi
