#!/bin/sh
# Recursivly list all git(1) repositories incl. their sizes under the
# given directory in parallel

find "${1}" -type d -name .git -printf '%h\0' \
	| xargs -0 -P0 -n5 -r \
		du -sh \
	| sort -k2
