#!/bin/sh
# Block entire services using iptables

# List of services to block.
as_list='
714	# Apple
8075	# Microsoft
15169	# Google
19679	# Dropbox
20940	# Akamai
32787	# Akamai (other)
32934	# Facebook
'
# Note the escaped &
api_url='https://stat.ripe.net/data/announced-prefixes/data.json?min_peers_seeing=0\&resource='

printf 'Fetch all associated networks for each service...\n'
networks=$(curl -s $(printf '%s' "${as_list}" \
			| tr -d -c '[:digit:]\n' \
			| sed "/^$/d; s,^,${api_url},g"
	) \
		| sed -n 's,^ *"prefix": "\(.*\)"$,\1,p'
)

setname=netblock

# Create sets to store IP addresses in
sudo ipset create "${setname}" hash:net family inet hashsize 4096
sudo ipset create "${setname}"6 hash:net family inet6 hashsize 4096

# Add sets to netfilter
sudo iptables -I OUTPUT 1 -m set --match-set "${setname}" dst -j REJECT
sudo ip6tables -I OUTPUT 1 -m set --match-set "${setname}"6 dst -j REJECT

printf 'Block IPv4 ranges...\n'
printf '%s' "${networks}" | grep -F . \
	| xargs -n 1 -I _net_ \
		sudo ipset add "${setname}" _net_

printf 'Block IPv6 ranges...\n'
printf '%s' "${networks}" | grep -F : \
	| xargs -n 1 -I _net6_ \
		sudo ipset add "${setname}"6 _net6_
