#!/bin/sh
# switch power state using dmenu

options='lock
poweroff
reboot
suspend
'

sel=$(printf '%s' "${options}" \
	| dmenu -f -i -l 4 \
)

printf '%s' "${options}" | grep -q -x "${sel}" \
	&& sudo ${sel}
