#!/bin/sh
# switch power state using dmenu

options='lock
lock-suspend
poweroff
reboot
suspend
'

sel=$(printf '%s' "${options}" \
	| dmenu -f -i -l 5
)

case "${sel}" in
	lock|lock-suspend)
		"${sel}"
		;;
	poweroff|reboot|suspend)
		sudo "${sel}"
		;;
esac
