#!/bin/sh
# set dwm's status bar

while (true)
do
	xsetroot -name "$(printf '%s  E: %s  W: %s  %d°C  %d%%  %s' \
		"$(sgetsong | cut -c-40)" \
		"$(getip $(ip -o link show \
				| awk -F: '/e(th|np)[0-9]/ { print $2 }'
			) \
			| tail -n1
		)" \
		"$(getssid)" \
		"$(gettemp)" \
		"$(getvol)" \
		"$(date '+%a %d.%m.%y %H:%M')"
	)"
	sleep 30
done
