#!/bin/sh
# Select a host defined in ssh_config(5) and optionally pass ssh(1)
# options or a command to execute remotely by editing the selection in
# dmenu(1)

ssh $(sed -n -e s/^Host\ //p "${HOME}"/.ssh/config \
		| sort -s \
		| dmenu -p Host: -l 10)
