#!/bin/sh
# Ensure that the program being symlinked from is always run
# inside a tmux(1) session. If already running, simply attach.
# Command line arguments are passed unmodified to the program upon
# spawning a new session.
#
# In case standard input is not a terminal, this script will try
# spawning a new one.
#
# USAGE:
#	$ ln -s $(which tmuxify) mutt
#	$ ./mutt -R	# run 'mutt -R' or attach to "mutt"

set -eu

# name of the program/symlink
name="${0##*/}"
# absoloute path to this script
self="$(readlink -fn "${0}")"
# first program in $PATH called $name
bin=
for p in $(which -a "${name}"); do
	# prevent recursion
	if [ "$(readlink -fn "${p}")" != "${self}" ]; then
		bin="${p}"
		break
	fi
done

# XXX: Detect terminal emulator reliably or drop this feature
term=
[ ! -t 0 ] && [ -n "${DISPLAY}" ] &&
	term='st -e'

if tmux has-session -t "${name}"; then
	exec ${term:-} tmux attach-session -t "${name}"
else
	exec ${term:-} tmux new-session -n "${name}" -s "${name}" \
		"${bin}" "${@}"
fi
