#!/bin/sh
# Attach to existing tmux session or run $PROGRAM inside newly spawned one
# USAGE:	$ ln -s tmuxify mutt && ./mutt

# The program's name
name="${0##*/}"
# This script's absoloute directory
path=$(readlink "${0}")
# First binary found in $PATH not being this script itself
exe=$(which -a "${name}" \
		| grep -v -E "^(${path%/*}|$(cd "${0%/*}" && pwd))" \
		| head -n1)

tmux has -t "${name}" \
	&& exec tmux attach -t "${name}" \
	|| exec tmux new -n "${name}" -s "${name}" \
		"${exe}" ${@}
