#!/bin/sh
# Stream video URL through youtube-dl reading stdin or shell arguments

if [ ${#} -gt 0 ]; then
	# Shell arguments
	youtube-dl "${1}" -o - | mpv -
elif [ ! -t 0 ]; then
	# stdin
	youtube-dl -a - -o - | mpv -
fi

exit
